#!/usr/bin/env bash

export DIA_LOG=$(date +%d%m%Y-%H%M%S)
FILE_LOG="/dados/Logs/iacl_$DIA_LOG.log"
DIR_LOCAL="/mnt/driver"
VERDE="\033[32;1m]"
VERMELHOP="\033[31;1;5m]"

function updateSystem () {
    apt-get update ; apt-get upgrade -y ; apt-get dist-upgrade -y ; apt autoremove
}

cd /var/lib/docker/volumes/app/_data/index.php
docker run --name web-server -dt -p 80:80 --mount type=volume,src=app,dst=/app/ webdeveloper/php-apache:alpine-php7
docker swarm init
#docker node ls
docker service create --name web-server --replicas 10 -dt -p 80:80 --mount type=volume,src=app,dst=/app/ webdevops/php-apache:alpine-php7
#docker service ps web-service
apt-get install nfs-server
echo '/var/lib/docker/volumes/app/_data/ *(rw,sync,subtree-check)' >> /etc/exports
exportfs -ar
showmount -e
mkdir /proxy
cd proxy
